# 編集する前にUMP閉じてなー！ どの設定が何をするかはまにゅある見てなー
# Close UMP before editing! See manual for documentation
# https://pipiraworld.web.fc2.com/ump/manual/
version: 2
language: en
midi:
  loaderThreads: 0
  loadNotesOnly: false
  usePlayThread: true
  synth: null
render:
  background: 0xc0c0c0
  font: Monospaced
  fpsLimit: 120
  height: 720
  renderInterval: 5.0
  resourcePack: null
  usePFAColors: false
  width: 1280
  overlay:
    opaque: false
    info:
      scale: 1.0
      type: DEFAULT
      position: TOP_RIGHT
      showDuration: false
    fps:
      type: SHOW_ALL
    desync:
      type: SHOW_NUMBERS
    loading:
      showMemoryUsage: false
ui:
  font: Yu Gothic UI
files:
  midi: C:\Users\oosga\Downloads\python-MidiToVirtualPianoMacro-master\midibulk\Calamity_Mod_OST__DM_DOKURO_-_Roar_of_the_Jungle_Dragon__Piano_solo_NEW_VERSION.mid
  ffmpeg: null
  resourcePacks: null
updateChecker:
  checkOnStartup: true
  branch: development
